# Generated by Django 4.2.3 on 2023-07-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentStocks",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "stock_name",
                    models.CharField(max_length=250, verbose_name="Заголовок акции"),
                ),
                (
                    "stock_description",
                    models.TextField(max_length=500, verbose_name="Описание акции"),
                ),
                (
                    "stock_image",
                    models.TextField(
                        max_length=250, verbose_name="ID изображения акции"
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Текущие акции",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mailing_name",
                    models.CharField(max_length=250, verbose_name="Заголовок рассылки"),
                ),
                (
                    "mailing_description",
                    models.TextField(max_length=500, verbose_name="Описание рассылки"),
                ),
                (
                    "mailing_image",
                    models.TextField(
                        max_length=250, verbose_name="ID изображения рассылки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.BigIntegerField(
                        default=1, unique=True, verbose_name="ID пользователя телеграм"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Имя пользователя"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=150, verbose_name="Username телеграм"),
                ),
                (
                    "user_email",
                    models.CharField(max_length=100, null=True, verbose_name="Email"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="bot_manage.user",
                        unique=True,
                    ),
                ),
                ("referrer_id", models.BigIntegerField()),
            ],
            options={
                "verbose_name": "Реферал",
                "verbose_name_plural": "Рефералы",
            },
        ),
    ]
