# Generated by Django 4.2.3 on 2023-07-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_manage", "0002_alter_referral_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="date_of_publication",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата рассылки"),
        ),
    ]
