# Generated by Django 4.2.3 on 2023-07-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_manage", "0003_mailing_date_of_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentstocks",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
        ),
        migrations.AlterField(
            model_name="currentstocks",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AlterField(
            model_name="referral",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
        ),
        migrations.AlterField(
            model_name="referral",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
    ]
